package primero;
// Generated 12-dic-2018 23:44:55 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Fotos generated by hbm2java
 */
public class Fotos implements java.io.Serializable {

	private int idfoto;
	private String nombre;
	private String descripcion;
	private String tematica;
	private Integer anio;
	private Integer precio;
	private Set publicacioneses = new HashSet(0);

	public Fotos() {
	}

	public Fotos(int idfoto) {
		this.idfoto = idfoto;
	}

	public Fotos(int idfoto, String nombre, String descripcion, String tematica, Integer anio, Integer precio,
			Set publicacioneses) {
		this.idfoto = idfoto;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tematica = tematica;
		this.anio = anio;
		this.precio = precio;
		this.publicacioneses = publicacioneses;
	}

	public int getIdfoto() {
		return this.idfoto;
	}

	public void setIdfoto(int idfoto) {
		this.idfoto = idfoto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTematica() {
		return this.tematica;
	}

	public void setTematica(String tematica) {
		this.tematica = tematica;
	}

	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	public Integer getPrecio() {
		return this.precio;
	}

	public void setPrecio(Integer precio) {
		this.precio = precio;
	}

	public Set getPublicacioneses() {
		return this.publicacioneses;
	}

	public void setPublicacioneses(Set publicacioneses) {
		this.publicacioneses = publicacioneses;
	}

}
