package primero;
// Generated 12-dic-2018 23:44:55 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Mediocomunicacion generated by hbm2java
 */
public class Mediocomunicacion implements java.io.Serializable {

	private int idmedio;
	private String nombre;
	private String direccion;
	private String email;
	private String telefono;
	private Set publicacioneses = new HashSet(0);

	public Mediocomunicacion() {
	}

	public Mediocomunicacion(int idmedio) {
		this.idmedio = idmedio;
	}

	public Mediocomunicacion(int idmedio, String nombre, String direccion, String email, String telefono,
			Set publicacioneses) {
		this.idmedio = idmedio;
		this.nombre = nombre;
		this.direccion = direccion;
		this.email = email;
		this.telefono = telefono;
		this.publicacioneses = publicacioneses;
	}

	public int getIdmedio() {
		return this.idmedio;
	}

	public void setIdmedio(int idmedio) {
		this.idmedio = idmedio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Set getPublicacioneses() {
		return this.publicacioneses;
	}

	public void setPublicacioneses(Set publicacioneses) {
		this.publicacioneses = publicacioneses;
	}

}
