package primero;
// Generated 12-dic-2018 23:44:55 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Publicaciones generated by hbm2java
 */
public class Publicaciones implements java.io.Serializable {

	private int idpublicacion;
	private Fotos fotos;
	private Mediocomunicacion mediocomunicacion;
	private Date fechaPublicacion;
	private String piePublicacion;

	public Publicaciones() {
	}

	public Publicaciones(int idpublicacion, Fotos fotos, Mediocomunicacion mediocomunicacion) {
		this.idpublicacion = idpublicacion;
		this.fotos = fotos;
		this.mediocomunicacion = mediocomunicacion;
	}

	public Publicaciones(int idpublicacion, Fotos fotos, Mediocomunicacion mediocomunicacion, Date fechaPublicacion,
			String piePublicacion) {
		this.idpublicacion = idpublicacion;
		this.fotos = fotos;
		this.mediocomunicacion = mediocomunicacion;
		this.fechaPublicacion = fechaPublicacion;
		this.piePublicacion = piePublicacion;
	}

	public int getIdpublicacion() {
		return this.idpublicacion;
	}

	public void setIdpublicacion(int idpublicacion) {
		this.idpublicacion = idpublicacion;
	}

	public Fotos getFotos() {
		return this.fotos;
	}

	public void setFotos(Fotos fotos) {
		this.fotos = fotos;
	}

	public Mediocomunicacion getMediocomunicacion() {
		return this.mediocomunicacion;
	}

	public void setMediocomunicacion(Mediocomunicacion mediocomunicacion) {
		this.mediocomunicacion = mediocomunicacion;
	}

	public Date getFechaPublicacion() {
		return this.fechaPublicacion;
	}

	public void setFechaPublicacion(Date fechaPublicacion) {
		this.fechaPublicacion = fechaPublicacion;
	}

	public String getPiePublicacion() {
		return this.piePublicacion;
	}

	public void setPiePublicacion(String piePublicacion) {
		this.piePublicacion = piePublicacion;
	}

}
