package primero;
// Generated 07-dic-2018 17:06:26 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro implements java.io.Serializable {

	private int codigoLibro;
	private String titulo;
	private String autor;
	private String editorial;
	private Integer anio;
	private String isbn;
	private Integer ejemplares;
	private Integer paginas;
	private Set<Prestamo> prestamos = new HashSet<Prestamo>(0);

	public Libro() {
	}

	public Libro(int codigoLibro, String isbn) {
		this.codigoLibro = codigoLibro;
		this.isbn = isbn;
	}

	public Libro(int codigoLibro, String titulo, String autor, String editorial, Integer anio, String isbn,
			Integer ejemplares, Integer paginas, Set<Prestamo> prestamos) {
		this.codigoLibro = codigoLibro;
		this.titulo = titulo;
		this.autor = autor;
		this.editorial = editorial;
		this.anio = anio;
		this.isbn = isbn;
		this.ejemplares = ejemplares;
		this.paginas = paginas;
		this.prestamos = prestamos;
	}

	public int getCodigoLibro() {
		return this.codigoLibro;
	}

	public void setCodigoLibro(int codigoLibro) {
		this.codigoLibro = codigoLibro;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	public String getEditorial() {
		return this.editorial;
	}

	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public Integer getEjemplares() {
		return this.ejemplares;
	}

	public void setEjemplares(Integer ejemplares) {
		this.ejemplares = ejemplares;
	}

	public Integer getPaginas() {
		return this.paginas;
	}

	public void setPaginas(Integer paginas) {
		this.paginas = paginas;
	}

	public Set<Prestamo> getPrestamos() {
		return this.prestamos;
	}

	public void setPrestamos(Set<Prestamo> prestamos) {
		this.prestamos = prestamos;
	}

}
