package primero;
// Generated 07-dic-2018 17:06:26 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo implements java.io.Serializable {

	private PrestamoId id;
	private Libro libro;
	private Socio socio;
	private Date fechaInicio;
	private Date fechaFin;

	public Prestamo() {
	}

	public Prestamo(PrestamoId id, Libro libro, Socio socio) {
		this.id = id;
		this.libro = libro;
		this.socio = socio;
	}

	public Prestamo(PrestamoId id, Libro libro, Socio socio, Date fechaInicio, Date fechaFin) {
		this.id = id;
		this.libro = libro;
		this.socio = socio;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
	}

	public PrestamoId getId() {
		return this.id;
	}

	public void setId(PrestamoId id) {
		this.id = id;
	}

	public Libro getLibro() {
		return this.libro;
	}

	public void setLibro(Libro libro) {
		this.libro = libro;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

}
