package primero;
// Generated 07-dic-2018 17:06:26 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Socio generated by hbm2java
 */
public class Socio implements java.io.Serializable {

	private int codigoSocio;
	private String nombre;
	private String apellidos;
	private Date fechaNac;
	private String domicilio;
	private String telefono;
	private Set<Prestamo> prestamos = new HashSet<Prestamo>(0);

	public Socio() {
	}

	public Socio(int codigoSocio) {
		this.codigoSocio = codigoSocio;
	}

	public Socio(int codigoSocio, String nombre, String apellidos, Date fechaNac, String domicilio, String telefono,
			Set<Prestamo> prestamos) {
		this.codigoSocio = codigoSocio;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fechaNac = fechaNac;
		this.domicilio = domicilio;
		this.telefono = telefono;
		this.prestamos = prestamos;
	}

	public int getCodigoSocio() {
		return this.codigoSocio;
	}

	public void setCodigoSocio(int codigoSocio) {
		this.codigoSocio = codigoSocio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Set<Prestamo> getPrestamos() {
		return this.prestamos;
	}

	public void setPrestamos(Set<Prestamo> prestamos) {
		this.prestamos = prestamos;
	}

}
