package primero;
// Generated 29-nov-2018 18:50:03 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private int idcliente;
	private String nombre;
	private String direccion;
	private String poblacion;
	private String telef;
	private String nif;
	private Set<Venta> ventas = new HashSet<Venta>(0);

	public Cliente() {
	}

	public Cliente(int idcliente, String nombre) {
		this.idcliente = idcliente;
		this.nombre = nombre;
	}

	public Cliente(int idcliente, String nombre, String direccion, String poblacion, String telef, String nif,
			Set<Venta> ventas) {
		this.idcliente = idcliente;
		this.nombre = nombre;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.telef = telef;
		this.nif = nif;
		this.ventas = ventas;
	}

	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getTelef() {
		return this.telef;
	}

	public void setTelef(String telef) {
		this.telef = telef;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public Set<Venta> getVentas() {
		return this.ventas;
	}

	public void setVentas(Set<Venta> ventas) {
		this.ventas = ventas;
	}

}
