package primero;
// Generated 29-nov-2018 18:50:03 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta implements java.io.Serializable {

	private int idventa;
	private Cliente cliente;
	private Producto producto;
	private Date fechaventa;
	private Integer cantidad;

	public Venta() {
	}

	public Venta(int idventa, Date fechaventa) {
		this.idventa = idventa;
		this.fechaventa = fechaventa;
	}

	public Venta(int idventa, Cliente cliente, Producto producto, Date fechaventa, Integer cantidad) {
		this.idventa = idventa;
		this.cliente = cliente;
		this.producto = producto;
		this.fechaventa = fechaventa;
		this.cantidad = cantidad;
	}

	public int getIdventa() {
		return this.idventa;
	}

	public void setIdventa(int idventa) {
		this.idventa = idventa;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Date getFechaventa() {
		return this.fechaventa;
	}

	public void setFechaventa(Date fechaventa) {
		this.fechaventa = fechaventa;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
